### ISSUE TITLE
Different animation rendering for flash and html5 targets 

### ISSUE THREAD

**Issue by VirtualMaestro** [openfl/away3d#18]
Hi guys,
There is an issue with animation rendering if you try to compile for html5 target. 
I checked the example of 'PolarBearAWDAnimation' -
https://github.com/openfl/away3d-samples/tree/master/intermediate/PolarBearAWDAnimation

(Original AS3 version was checked and there everything is ok)

I'm using **Away3d 5.0.4**, **OpenFL 7.0.0** and **Lime 6.0.1**.
The following target platforms were checked:
- **FLASH** target (animation looks the same as in original as3 version (correct));
- **HTML5** target (animation looks incorrect - Bear model is "floating");
- **NEKO** (Bear didn't load and some exception was thrown).

I've recorded a video where you can see the difference (from left to right):
 -- original AS3 version -- haxe version target to FLASH -- haxe version target to HTML5
[BearsTest.zip](https://github.com/openfl/away3d/files/1646674/BearsTest.zip)

Maybe you can help to fix this (for html5) or at least give a hint where to look for a solution.

Thank you in advance

**Comment by jgranick** [comment]
Thanks for the report! One of our shader initialization values was initializing as `null` (and not assigned value), so it caused trouble later throughout the code. Works here on Neko and HTML5 as well as Flash for me

**Comment by VirtualMaestro** [comment]
Thanks a lot!

**Comment by VirtualMaestro** [comment]
Now Neko is working well with the correct animation (like in flash). But unfortunately in html5 mesh is still "floating" (It looks like rubber bear with water inside). Maybe the last video didn't show it well, so I recorded another one (left bear is running on Neko and looks good, the right one is on html5 and looks wrong). 
[Two bears.zip](https://github.com/openfl/away3d/files/1649169/Two.bears.zip)
If you don't have such effect can you tell me what version of Lime and Openfl are in use? Which version of a browser are you running this example on? This will be very helpful. Thank you in advance.
