### ISSUE TITLE
100$ Bounty with fix during next 10 days. Mipmaps performance on html5 is bad.

### ISSUE THREAD

**Issue by xoopx** [openfl/away3d#21]
Hi, mipmaps performs very bad on html5. If i only render 20 planes with mipmaps, fps drops to 25 on html5, while in flash i can render 200 planes with mipmaps at 60fps. I attach example project.
[MipMappingPerformance.zip](https://github.com/openfl/away3d/files/2041505/MipMappingPerformance.zip)

**Comment by Greg209** [comment]
Using the code in the OpenFL PR https://github.com/openfl/openfl/pull/1906 stops the mipmaps being regenerated for every texture on every frame. Hopefully this helps improve the performance on the HTML target as generating mipmaps is a slow process.

The PR fixes a bug where any value other than the defaults for texture sampler states were causing them to be marked as dirty.

Check it out and see if it improves performance.

Also to note. The example you posted uses the DOM target. Comment out or remove the line from the project.xml as the best supported target with the latest OpenFL is the default webgl target.

Let me know how you get on.

**Comment by xoopx** [comment]
Thanks, that's what I need, send your paypal please.

**Comment by xoopx** [comment]
Did you recieved money?

**Comment by Greg209** [comment]
Yes - just arrived. Thanks again.
