### ISSUE TITLE
How to play animation in Dae format?

### ISSUE THREAD

**Issue by rainyt** [openfl/away3d#34]
I created a cat.dae using Blender and animated wait, but I can't play it. Do I need to set some configurations when exporting?

**Comment by rainyt** [comment]
```haxe
loader = new Loader3D();
		loader.addEventListener(LoaderEvent.RESOURCE_COMPLETE, (event) -> {
			view3d.scene.addChild(loader);
			loader.scale(300);
			loader.y += 100;
			animator = new SkeletonAnimator(animationSet, skeleton);
			mesh.animator = animator;
			animator.play("node_0");
			animator.autoUpdate = true;
		});
```
I used this layer of code, but there is no animation, even the picture is distorted.

![image](https://user-images.githubusercontent.com/9693090/65498555-b3b3d280-deee-11e9-8d43-8ca5a608780a.png)

**Comment by player-03** [comment]
I started digging into this and fixing bugs. I haven't fixed everything yet, but I've successfully gotten an animation to play. Try pull request #40 and see if it helps.

**Comment by rainyt** [comment]
> I started digging into this and fixing bugs. I haven't fixed everything yet, but I've successfully gotten an animation to play. Try pull request #40 and see if it helps.

This doesn't seem to help, is there no bones for loading dae? parentPose is null.

**Comment by rainyt** [comment]
[cat2.dae.zip](https://github.com/openfl/away3d/files/5501042/cat2.dae.zip)
Error DAE file.

**Comment by player-03** [comment]
Thanks for the example file! I don't have time to look at this right now, but I definitely want to get to it.

**Comment by rainyt** [comment]
Thanks, if you have any news, please let me know.

**Comment by rainyt** [comment]
[video.zip](https://github.com/openfl/away3d/files/5507740/video.zip)
This is the performance of animation.

**Comment by rainyt** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/9693090/98618968-34c16980-233d-11eb-8476-c6bdaec33bdd.png">
Good news! The current check is that the id of all animations is always empty characters, which causes an error.

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/98619470-448d7d80-233e-11eb-8c09-c4146074bf68.png)
Animate is ok now! @player-03 
I will create a pull request.
