### ISSUE TITLE
problem with shadow effects

### ISSUE THREAD

**Issue by sourceskyboxer** [openfl/away3d#5]
away3d example load3DS doesn't show if I use openfl test windows than it doesn't show like black screen

Can you fix it?

I'm using OpenFL 4.9.1, Lime  4.0.2, HXCPP 3.4.64 and Haxe 3.4.2
And I am using with Visual Studio 2015 Community
![where_is_load3ds](https://cloud.githubusercontent.com/assets/3496136/24323300/dac6028a-1173-11e7-9443-a48979fce4da.JPG)

Thanks

**Comment by jasonsturges** [comment]
@sourceskyboxer I believe Josh fixed this - update lime haxelib

**Comment by sourceskyboxer** [comment]
Oh thanks for fix I will check

**Comment by jasonsturges** [comment]
@Greg209 @jgranick This looks ready to close.
